### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by CiscoPress** [OTGApps/Hacker-Bar#46]
I don't want to purchase RubyMoation (Closed Source). Please upload Binary releases.

**Comment by markrickert** [comment]
Hey Cisco Press, thanks for your interest in Hacker Bar. I sell the app for $1.99 (less than a cup of Starbucks Coffee) in the Mac app store. The source code is here for other RubyMotion developers to learn from. Hacker Bar is open source, however it is not free (since I make my living writing Mac and iPhone apps). I won't be uploading non-app store binaries. 

Thanks again for reaching out!

you can purchase Hacker Bar here: https://itunes.apple.com/us/app/hacker-bar/id752399442?mt=12&uo=4&at=10l4yY&ct=github

-Mark

**Comment by twerth** [comment]
:+1:

**Comment by CiscoPress** [comment]
I bought it and rated 5 stars. Thanks.

**Comment by markrickert** [comment]
Awesome! Thanks so much!
